### ISSUE TITLE
执行 npm run dev: h5时报错

### ISSUE THREAD

**Issue by meiyzeng** [NervJS/taro-todomvc-hooks#1]
clone 项目 npm install 后 执行 npm run dev: h5时报错了
![image](https://user-images.githubusercontent.com/9260882/57361929-2d515b00-71b0-11e9-934f-8251afbaf33b.png)

**Comment by IEfucker** [comment]
也报错了

(node:15580) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'enableDll' in E:\workspace\test\Taro\taro-todomvc-hooks
    at Object.<anonymous> (E:\workspace\test\Taro\taro-todomvc-hooks\node_modules\@tarojs\webpack-runner\dist\index.js:108:25)
    at Generator.next (<anonymous>)
    at E:\workspace\test\Taro\taro-todomvc-hooks\node_modules\@tarojs\webpack-runner\dist\index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (E:\workspace\test\Taro\taro-todomvc-hooks\node_modules\@tarojs\webpack-runner\dist\index.js:3:12)
    at exports.default (E:\workspace\test\Taro\taro-todomvc-hooks\node_modules\@tarojs\webpack-runner\dist\index.js:98:31)
    at Compiler.<anonymous> (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\dist\h5\index.js:153:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@tarojs\cli\dist\h5\index.js:4:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by schizobulia** [comment]
### 已解决
- taro update self
- 然后到项目目录下执行taro update project
- npm run dev:h5 即可
